### ISSUE TITLE
Dropdown in DMs

### ISSUE THREAD

**Issue by danbovey** [danbovey/EmojiPanel#2]
Currently there is no support for adding emojis in the Messages form.

**Comment by vphantom** [comment]
This is actually a regression from a previous version: I was able to insert emoji in direct messages as recently as November 9th, 2016.  A recent update (which added new emoji and searching, nice!) seems to have removed that capability.

I'm guessing the recent merge with EmojiT is related.

**Comment by danbovey** [comment]
Yep. Apologies about that. I'll work on this next.
