### ISSUE TITLE
npm package empty

### ISSUE THREAD

**Issue by eramdam** [danbovey/EmojiPanel#20]
When installing with npm, the content of the package is empty, there's only a `package.json` and an `.npmignore` file. See

```
damien@Oreo:~/D/S/electron-quick-start
<master✓> » npm i emojipanel
npm notice created a lockfile as package-lock.json. You should commit this file.
+ emojipanel@1.0.0
added 1 package in 0.96s
damien@Oreo:~/D/S/electron-quick-start
<master✗> » ll node_modules/emojipanel
total 16
drwxr-xr-x 4 damien staff  136  1 Oct   09:59  .
drwxr-xr-x 3 damien staff  102  1 Oct   09:59  ..
-rw-r--r-- 1 damien staff   12 27 Dec    2016  .npmignore
-rw-r--r-- 1 damien staff 1.4K  1 Oct   09:59  package.json
damien@Oreo:~/D/S/electron-quick-start
<master✗> »
```

**Comment by danbovey** [comment]
Haven't published any actual stuff onto npm yet as this is still in development. The panel doesn't write emojis into an input so it's a bit useless in it's current state. Sorry for the confusion.

**Comment by simonpeters** [comment]
I suggesting adding this info to the read me

**Comment by dorcilio** [comment]
O projeto foi descontinuado?
Ainda não está disponível no NPM.
