### ISSUE TITLE
Alpha release

### ISSUE THREAD

**Issue by mentos1386** [danbovey/EmojiPanel#26]
Hey, i want to use this project even if it's not stable yet. Could you make an alpha (or 0.x) release for those that don't mind using it even if its unstable?

**Comment by mentos1386** [comment]
I am looking for framework independent solution (or angular 2+). I would use your emoji panel inside angular. It's a bit harder to do that with react components (afaik).

But, that draft-js is actually exactly what i'm trying to create :D Maybe i should switch to react...

**Comment by danbovey** [comment]
Ah sorry, I thought it was vanilla js. There's definitely a gap in the market for a package like this, hence the 50 stars on a basically empty project. Unfortunately, I don't have the time to work on it right now.

**Comment by mentos1386** [comment]
Yeah, angular struggles with emoji support as well... If  i don't find any other solution (and i don't move to react) i might make couple of PR.
